"""create tasks table

Revision ID: 2b3580f9fb6d
Revises: ac009f8ae998
Create Date: 2026-02-25 01:35:27.545630

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b3580f9fb6d"
down_revision: Union[str, Sequence[str], None] = "ac009f8ae998"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.Enum("NEW", "PROCESSING", "DONE", "FAILED", name="task_status"), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="tasks",
    )
    op.create_index(op.f("ix_tasks_tasks_status"), "tasks", ["status"], unique=False, schema="tasks")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_tasks_status"), table_name="tasks", schema="tasks")
    op.drop_table("tasks", schema="tasks")
    # ### end Alembic commands ###
